<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLb4f5u7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLb4f5u7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLb4f5u7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLb4f5u7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLb4f5u7\appProdProjectContainer(array(
    'container.build_hash' => 'Lb4f5u7',
    'container.build_id' => '1f2bf645',
    'container.build_time' => 1542015231,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLb4f5u7');
